version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: sh -c "sleep 5 && poetry run python manage.py makemigrations && poetry run python manage.py migrate --noinput && poetry run python manage.py runserver 0.0.0.0:8000 --settings=settings.settings"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}

volumes:
  pgdata:
