# Generated by Django 5.0.7 on 2024-07-18 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, verbose_name="название пункта"),
                ),
                (
                    "additional_info",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        null=True,
                        verbose_name="дополнительная информация",
                    ),
                ),
                ("longitude", models.FloatField(verbose_name="Долгота")),
                ("latitude", models.FloatField(verbose_name="Ширина")),
                ("last_visited", models.DateTimeField(auto_now=True)),
                (
                    "counter",
                    models.IntegerField(default=1, verbose_name="Количество посещений"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "search_history",
            },
        ),
    ]
